import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import NavBar from '@/components/NavBar'
import Footer from '@/components/Footer'
import { NextAuthProvider } from '@/components/Providers'
import { Toaster } from 'react-hot-toast'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} lg:max-w-[900px] lg:px-16 px-8 mx-auto py-8 shadow-xl min-h-screen flex flex-col`}> 
        <NextAuthProvider>
          <div>
            <NavBar />        
              <div className='flex-auto'>
                {children}
              </div>
            <Footer />
          </div>
          
          <Toaster />
        </NextAuthProvider>
        
      </body>
    </html>
  )
}
